### ISSUE TITLE
写真の類似度の判定でZeroDivisionErrorが出る

### ISSUE THREAD

**Issue by myabu-dev** [Mokumoku-Rin/RinRinRun#150]
postの内容
landmark_id: 2
course_id: 1
img: "iVBORw0KGgoAAAANSUhEUgAAASwAAACWCAYAAABkW7XSAAAgAE......"

```
mokumoku-python | INFO:     172.24.0.1:39564 - "POST /session/landmark/visit/ HTTP/1.1" 500 Internal Server Error
mokumoku-python | ERROR:    Exception in ASGI application
mokumoku-python | Traceback (most recent call last):
mokumoku-python |   File "/usr/local/lib/python3.8/site-packages/uvicorn/protocols/http/httptools_impl.py", line 385, in run_asgi
mokumoku-python |     result = await app(self.scope, self.receive, self.send)
mokumoku-python |   File "/usr/local/lib/python3.8/site-packages/uvicorn/middleware/proxy_headers.py", line 45, in __call__
mokumoku-python |     return await self.app(scope, receive, send)
mokumoku-python |   File "/usr/local/lib/python3.8/site-packages/fastapi/applications.py", line 149, in __call__
mokumoku-python |     await super().__call__(scope, receive, send)
mokumoku-python |   File "/usr/local/lib/python3.8/site-packages/starlette/applications.py", line 102, in __call__
mokumoku-python |     await self.middleware_stack(scope, receive, send)
mokumoku-python |   File "/usr/local/lib/python3.8/site-packages/starlette/middleware/errors.py", line 181, in __call__
mokumoku-python |     raise exc from None
mokumoku-python |   File "/usr/local/lib/python3.8/site-packages/starlette/middleware/errors.py", line 159, in __call__
mokumoku-python |     await self.app(scope, receive, _send)
mokumoku-python |   File "/usr/local/lib/python3.8/site-packages/starlette/middleware/cors.py", line 84, in __call__
mokumoku-python |     await self.simple_response(scope, receive, send, request_headers=headers)
mokumoku-python |   File "/usr/local/lib/python3.8/site-packages/starlette/middleware/cors.py", line 140, in simple_response
mokumoku-python |     await self.app(scope, receive, send)
mokumoku-python |   File "/usr/local/lib/python3.8/site-packages/starlette/exceptions.py", line 82, in __call__
mokumoku-python |     raise exc from None
mokumoku-python |   File "/usr/local/lib/python3.8/site-packages/starlette/exceptions.py", line 71, in __call__
mokumoku-python |     await self.app(scope, receive, sender)
mokumoku-python |   File "/usr/local/lib/python3.8/site-packages/starlette/routing.py", line 550, in __call__
mokumoku-python |     await route.handle(scope, receive, send)
mokumoku-python |   File "/usr/local/lib/python3.8/site-packages/starlette/routing.py", line 227, in handle
mokumoku-python |     await self.app(scope, receive, send)
mokumoku-python |   File "/usr/local/lib/python3.8/site-packages/starlette/routing.py", line 41, in app
mokumoku-python |     response = await func(request)
mokumoku-python |   File "/usr/local/lib/python3.8/site-packages/fastapi/routing.py", line 147, in app
mokumoku-python |     raw_response = await run_endpoint_function(
mokumoku-python |   File "/usr/local/lib/python3.8/site-packages/fastapi/routing.py", line 101, in run_endpoint_function
mokumoku-python |     return await dependant.call(**values)
mokumoku-python |   File "/src/api/routers/sessions/landmark.py", line 14, in compare_image
mokumoku-python |     message = await LandmarkService.ImageCompare(landmark_request)
mokumoku-python |   File "/src/api/services/landmark.py", line 8, in ImageCompare
mokumoku-python |     similarity = calc_image_similarity(
mokumoku-python |   File "/src/api/usecases/image.py", line 46, in calc_image_similarity
mokumoku-python |     ret = sum(dist) / len(dist)
mokumoku-python | ZeroDivisionError: division by zero
```

出たり出なかったりする
最新のDevelopを使用
原因は不明

**Comment by myabu-dev** [comment]
稀によく起こる

**Comment by kibehiro** [comment]
len(dist)が0になるってなんだ
特徴量が取れないってことか？

**Comment by hiragi-gkuth** [comment]
特徴量が一つも取れなかったということ，
それは類似度が低いことをおそらく示しているので，distの長さが0の場合は無条件でNGにする対応をする

**Comment by hiragi-gkuth** [comment]
対応済み
